### ISSUE TITLE
Convert the manual

### ISSUE THREAD

**Issue by omasanori** [omasanori/franz-lisp#2]
It would be great if the manual could be browsed on web, using e.g. Read the Docs.

**Comment by omasanori** [comment]
I just started: https://franz-lisp.readthedocs.io/

**Comment by omasanori** [comment]
I found that the PDF version of the manual available on Software Preservation Group render equations incorrectly. Porting the original manual to *modern* roff to produce proper PDF may also be desired.
(Sphinx can produce PDF too, but it is hard if not impossible to keep the original layout.)

**Comment by krytarowski** [comment]
A friend of mine has printed version of manuals, perhaps proprietary ones from the time of Franz Lisp company (and before the move to Common Lisp). I will try to research whether something of it could be shared.

**Comment by krytarowski** [comment]
Just a note, we probably might use the naming Franz for our resurrected or maintained code, however for new projects we shall use a different name. There is still the Franz company around selling Allegro Common Lisp.

**Comment by omasanori** [comment]
@krytarowski Yes, definitely.

**Comment by omasanori** [comment]
Removed Read the Docs page temporarily, I will enable it again after we choose a new name.

**Comment by omasanori** [comment]
Then, documentation conversion activities moved to reconstruct-doc branch, to avoid showing half-baked works on the default branch.

By the way, I think that it is better to put the manual to separate repository because the license of the manual is different from the code and it does not satisfy [The Open Source Definition](https://opensource.org/osd):

> Permission to copy without fee all or part of this material is granted provided that the copies are not made or distributed for direct commercial advantage, and the copyright notice of the Regents, University of California, is given. All rights reserved.

Since machine-dependent description in the manual will not match if we port the code to modern computers, separation is good for both whom want to read the original manual and whom want to port the code to new systems. Any thoughts?

**Comment by omasanori** [comment]
Closed as the manual is not BSD licensed anyway.
